
from .hunyuan_3d_node import Hunyuan3DImageTo3D
from .embedding_algebra import (
    NODE_CLASS_MAPPINGS as ALGEBRA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ALGEBRA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .embedding_algebra_extended import (
    NODE_CLASS_MAPPINGS as EXTENDED_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXTENDED_NODE_DISPLAY_NAME_MAPPINGS,
)
from .embedding_mixer import (
    NODE_CLASS_MAPPINGS as MIXER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MIXER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .embedding_tree import (
    NODE_CLASS_MAPPINGS as TREE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TREE_NODE_DISPLAY_NAME_MAPPINGS,
)

Hunyuan3DImageTo3D.install_check()

NODE_CLASS_MAPPINGS = {
    "Hunyuan3D2ImageTo3D": Hunyuan3DImageTo3D,
    **ALGEBRA_NODE_CLASS_MAPPINGS,
    **EXTENDED_NODE_CLASS_MAPPINGS,
    **MIXER_NODE_CLASS_MAPPINGS,
    **TREE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "Hunyuan3D2ImageTo3D": "Hunyuan3D-2 Image to 3D",
    **ALGEBRA_NODE_DISPLAY_NAME_MAPPINGS,
    **EXTENDED_NODE_DISPLAY_NAME_MAPPINGS,
    **MIXER_NODE_DISPLAY_NAME_MAPPINGS,
    **TREE_NODE_DISPLAY_NAME_MAPPINGS,
}
